### ISSUE TITLE
HingeLoss?

### ISSUE THREAD

**Issue by zygmuntz** [kastnerkyle/kaggle-dogs-vs-cats#1]
Maybe you could also publish HingeLoss code.

**Comment by kastnerkyle** [comment]
It is published in my pylearn2 fork under branch svm_layer - see models/mlp.py . I am hoping to get it integrated to the main pylearn2 stream eventually

**Comment by kastnerkyle** [comment]
Also some good discussion on the pylearn2-dev mailing list

https://groups.google.com/forum/#!topic/pylearn-dev/D2mZVB231Yg

**Comment by zygmuntz** [comment]
Thanks.
